forgejo_db_password: ENC[AES256_GCM,data:WgNfMta3PqDKNVjSeeqv3I6OpOsnzzo0lPGi3118xw1P6aVqeCQe7PuSprCZKach,iv:Guesj7wyItRTw6ttHZUxKeoCPsfDuXCLMz/yjYZG8Ak=,tag:eVfTyJZ2wjMwg8wtQrPmRA==,type:str]
forgejo_oauth_client_secret: ENC[AES256_GCM,data:1Sk4QDoGkkMmjWU9K6miPJiatKyu0gnOgWTv0yrq8z8gt9KLevlB0f44Qyyf0jUu,iv:tggw4f7JOPd78GummKjBuhIqsvVSLV6gsJ/JrezCrsk=,tag:kDxasud/sUSMAlN9/L5AMw==,type:str]
traefik_acme_email: ENC[AES256_GCM,data:q6t0fbHRPvfvLOWv4OoOPCW5gnXaBZzX5EA=,iv:0GpinexL9OG7iGzdW1jlha2Q30qaIYsBsl93oy/CiO4=,tag:q0gDnjiNIWZjdAXziagq5w==,type:str]
traefik_environment_vars:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:/tHngQTj6V23aUouHvnQ0I0vOJEaS4kMcz9DKlXWapPJrHcv6lo7Jg==,iv:22hrHVutEnkP4TKXbyFQBSVIyjw5oU+G5p4tZyWx27k=,tag:Fpne7GgjTLy6kF4wZP1SZw==,type:str]
sops:
    lastmodified: "2025-12-20T14:42:43Z"
    mac: ENC[AES256_GCM,data:dxWIKuK+zeE0//UUFLgF765Z1kqAl9aL2+r+YFI2MNfQKequQQmOmwddKHHVkGvpqAVh3JVLKtqrI0X7R74Tj9MObVbYCx7XY9DfLffL3hmCWeh/XynSym4PXrwPK3HQiqFEiqyXyjqz7jcsFcJP2hyFJkJKP8WRsrt8Taj2A2U=,iv:CUWbayTyIbEcaaj8IYKIGyUyDuAF/9NSCW2NLDNXn90=,tag:qNoGYeVBAGkfmKi83xQ9Xw==,type:str]
    pgp:
        - created_at: "2025-12-20T14:38:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdAEgHqdesZAXbg/RWKdImBJZ7PQgx/5qkPJymoX0tktAww
            7iZp+edO3DVDuAY7XYnEgspM/5BwJrU8nW1soWX3r9jRkEut6A3OsiZN8vpeMkck
            0lwBsne7Efb9UYWr47O6BSWGM2CuS9kWUXHtOoGpx/SdH0rFArisWIJicgSJUuby
            rzBlKDSlj3YarThNqtXW7a3UG3b7N5mqMTUEB8VTI54Ne/ZwR7iVhfcq0JusJw==
            =HTaz
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.11.0
