vaultwarden_admin_token: ENC[AES256_GCM,data:Fj7czzKHVyfO5AutlkpXxFlP/Unx+CcFRAWn1JlZzRGN4+5oQ+dc+6ZwmusmJeNg6sJnKw1rbDc1FiXuGUbdhzJoNqpdCgJSqtUhUXplGog3XlKKo906ypNNjNEoz/b8oDoamR/2Jjyui96agS0DZxJ2gsFNytPfKk+BFlEwR+fzKuDEO1w=,iv:SS90aTGCA6sCkVD3JnqWogz9FaBwIADZdF+Q/9Cj07Y=,tag:DS0O+TCK96/EHDGMRzNqWw==,type:str]
traefik_acme_email: ENC[AES256_GCM,data:3Vz5GYrkMQB1srBkKxuKKiuv3GKRnxz/dL8=,iv:FJeJnhsNN9+7sqRsLDudtU3DO8O+NbyiW4oL3xiDEZw=,tag:jT5D7uvepHhhK0kPnvLzhg==,type:str]
traefik_environment_vars:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:6dxYvB4br76147aDu/WzoFVh/NMLunApWlGa94mtDSeJ+UmYtgmIFA==,iv:akeq4OJ2vHYWQ9SYybEKDqi8SLlSEDmn72PxvHAgKIE=,tag:VSKNu42GPHAa1ufVnQuc/Q==,type:str]
sops:
    lastmodified: "2025-12-20T14:38:20Z"
    mac: ENC[AES256_GCM,data:hfYatYUF3t4TGw4FYUWkwID9FbMPupBZ8uvw1fbBqKZwMvQB/d2+LbbIY/B/ypDMlsF7jYFXyQpFJOdG/+gUPQn5F5WlRprWbpJOJFlU9DHnlLpAO6nGNgTUwfVazlxYAJpLS1bbXSQuGu7D+WRhyNE8hITaFtu/xFipI7F2P3A=,iv:QnxLYbOY6EucYPNuZSvU90kJnYH662NFZDr9Uw9X0Oc=,tag:Q+6VcV6bEti+HkdHsQ2MnQ==,type:str]
    pgp:
        - created_at: "2025-12-20T14:38:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdAvpfmxALfORt+ELeYiwS7vgzKN6armVWThYa93eNQvR0w
            rOvgfca8DYqa2nJ0ToH7JXVsP8T0Xqsjxlv/aY8znxqP5qSFNqvV03n08nvc6B87
            0l4BT5SHMpAb7Ey8Gl+OnbzzQ1JmXkjpZRhYO24ioF5ni6bRTNQEPy005lWBYNPU
            IK1peHA9wXOcOooZNy+aHURXmbHFt4Cu1cQhNTJ01P4GUF6uHhR0yXq4PP+1Y40x
            =rD9K
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.11.0
