cfdyndns_api_token: ENC[AES256_GCM,data:1biN7H+G8enF66OSUpwVa2CdIXgVx0Ucd5gksHcNk4GWChLNm57rUQ==,iv:GRRnLRXvflpEvBunD0Bu97HkHsGE7rdzb8Lfwk64FbI=,tag:jroFxIpFXkeTmAiMX8MlaA==,type:str]
cfdyndns_update_url: ENC[AES256_GCM,data:7IZQO1h5IhJSxUTxA5QBv1WVwdXz3MBozvzKIo7YCK/XKVRpXj0VENZHNAGO99/PsFAYylejpK+9,iv:U8lpXjXUeH53V8anejBViJqyKCBXSIq99712QxUS6+I=,tag:aCS/jDn5eFprqV0gBqfQaQ==,type:str]
sops:
    lastmodified: "2026-01-02T13:51:56Z"
    mac: ENC[AES256_GCM,data:Uf98SSPfK1obP/Bqm8opQdjcRWCfYqHx3gs/92qS1KnI4IFSflXKO8aJO17C4eg0zh+ZKv9IX1bcru9T8G6qwUTS3E/ZWxgVzVdAOxfVAaz2cVD2lZP17ZgUtUb+pbkYS42H9P1npEQCgAgQtr5xkhv7nLdX8hUb3zcbfajRe48=,iv:Wz6W8NVDxccHM2bgPjwwMRuTaWWIFHXj/10+tuIYgxY=,tag:evJeOSiNku0umc6ctJGs2A==,type:str]
    pgp:
        - created_at: "2026-01-02T13:50:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdA0cNpPVXgVBD8lG0yL4HpV/0QVJaMCIykB3484q2wenAw
            Ix2+GvQvyqTNq+o1VLWwOU7y4c+gbMPBEYkur6sTWDdIPMkgZal37PoAmTidyX9G
            0l4B2P8sJND098vQfCsaEGr8ViTChhmY7GMTm1dg7qjxUqJ7E5ifXsxUu0y7kZ0D
            AIPGzRtULNMSf/PUOIHcfnreL00QQudAQ361LlXdRK+Xn3QLY5RmJxp/2Lwt5TMX
            =xTgU
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.11.0
