---
# yamllint disable rule:line-length

######################################
### giftpilz0.general.timezone

timezone_timezone: Europe/Berlin

######################################
### giftpilz0.general.packages

packages_rpmfusion_package_state: skip
packages_python_package_state: skip
packages_flatpak_repo_state: skip

packages_additional_package:
  - bash-completion
  - epel-release
  - git-core
  - mkpasswd
  - nfs-utils
  - nmap

######################################
### giftpilz0.general.user

admin_group: "{{ 'wheel' if ansible_os_family == 'RedHat' else 'sudo' }}"

user_key_target_users:
  - container

user:
  - user_username: "serveradmin"
    user_groups:
      - "{{ admin_group }}"
      - serveradmin
    user_home: true
    user_shell: "/bin/bash"
    user_comment: "serveradmin"
    user_install_key_to_targets: true
    user_sudo_pwless: true
    user_state: present
    user_password: "!"
    user_pub:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOAhl7NUVzPjYfk/rB+dS0i6wDPkB5EtlZSfVwGdrWsg"

  # Additional users

  - user_username: "container"
    user_groups:
      - container
    user_home: true
    user_shell: "/bin/bash"
    user_comment: "container"
    user_install_key_to_targets: false
    user_sudo_pwless: false
    user_state: present
    user_password: "!"
    user_pub: []
