# IDP Service Configuration

clients:
{% for client in opencloud_oidc_clients %}
- id: {{ client.id }}
  name: {{ client.name }}
  trusted: {{ client.trusted | lower }}
  secret: "{{ client.secret }}"
  redirect_uris:
{% for uri in client.redirect_uris %}
  - {{ uri }}
{% endfor %}
{% if client.post_logout_redirect_uris | default([]) | length > 0 %}
  post_logout_redirect_uris:
{% for uri in client.post_logout_redirect_uris %}
  - {{ uri }}
{% endfor %}
{% else %}
  post_logout_redirect_uris: []
{% endif %}
{% if client.origins | default([]) | length > 0 %}
  origins:
{% for origin in client.origins %}
  - {{ origin }}
{% endfor %}
{% else %}
  origins: []
{% endif %}
  application_type: {{ client.application_type | default('""') }}
{% endfor %}
