mosquitto_pwfile_users:
    homeassistant: ENC[AES256_GCM,data:xcI1rb6cHRzZ1wxYKZngcH4X3h6sxov8CcLUoGkzUBGHRE0UvTqaYXmmqh0dyCPfURjzU0rKXB8vq4I5Z09yv9wJK1GGDdDatIWxY/xCRnSlUCkh1fqehTLAasq0/IWJETVBmoNqegImLipwMZcAkg==,iv:u705Ee4oMGaGHTfFwFv2KGYUQx9uIkhVur0uso7veBg=,tag:NaM4B1dc9lflVTEx7/crhA==,type:str]
traefik_acme_email: ENC[AES256_GCM,data:q/FBcctAY2Zmg8BLE1w61lzb0HMZLkSh/LA=,iv:skRi4z7YeWGFOwIZyOb1z2xMrL2K7NlGA30EqY2v8k8=,tag:tP5EGwEmdKCn0V0/VF8/dg==,type:str]
traefik_environment_vars:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:gZDEHKRkh315HdnanOabx8l7xCooh+b7hhexfm43E+N8XWA3px3W2w==,iv:WuX+Te45NKQIqoRGp2tz63MZ61nNSMaLZeet23fyKbY=,tag:P6QMXVRYZB3aIUZBX8zIiQ==,type:str]
sops:
    lastmodified: "2025-12-20T14:38:20Z"
    mac: ENC[AES256_GCM,data:vbr/EmtbAP/wVdgICAqm12UlBcmyrq6Hi4VEIFGz3/wkHcKyTptvMMqDOJPT9Aurcpn4Gygtggb7yTJPjpwojBfS0rMZReXmmCUJbRcYKNMys3IrY7qxP7mf2dxf4yzRpIX8oBtgFjDzsC1OpauXW7t+yZIdsmHlWIbcXn1t2Go=,iv:Lya2bYvbPS2vBMZM62QwApXdeuJbyp46aoCehllgl2E=,tag:Z7BtxMPG4UC3jqzTnhYJOQ==,type:str]
    pgp:
        - created_at: "2025-12-20T14:38:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdAb+Rd871Of3YGFsv7PkEcgozdAJT+SrvHoCBho6USCz0w
            /l2oOOBMOnGxYh5TQn2ILSEk4dB9IWpyzj+UzWzkQTj4rrkScD3G0LnaVdQgXc4y
            0l4BFWUUVsxIdC12uKC5+zf9PU98y2MEu1mvBPvFJMtfPy/EsjEUWGJqmPAENTUs
            iEteWsFRTdUgZI0OeNWKHZthmATyEjGU6ffYmF3SX8SkCiwl9iQPrdwYaQutZBdp
            =0mfE
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.11.0
