---
######################################
### giftpilz0.general.firewalld

firewalld_zones_define:
  - zone: server
    source: 192.168.60.0/24
  - zone: server-kubernetes
    source: 192.168.65.0/24
  - zone: server-lb
    source: 192.168.70.0/24
  - zone: clients
    source: 192.168.10.0/24
  - zone: clients
    source: 192.168.15.0/24
  - zone: iot-trusted
    source: 192.168.30.0/24

firewalld_rules_services:
  - service: ssh
    zone: clients
    state: enabled
  - service: http
    zone: clients
    state: enabled
  - service: https
    zone: clients
    state: enabled

firewalld_rules_ports:
  - port: 9001
    protocol: tcp
    zone: clients
    state: enabled
  - port: 1883
    protocol: tcp
    zone: clients
    state: enabled
  - port: 9001
    protocol: tcp
    zone: iot-trusted
    state: enabled
  - port: 1883
    protocol: tcp
    zone: iot-trusted
    state: enabled

######################################
### giftpilz0.server.podman, giftpilz0.homelab.homeassistant

podman_user: "container"

mosquitto_version: "2"
homeassistant_version: "2025.12"

mosquitto_autoupdate: true
homeassistant_autoupdate: true

homeassistant_device: "/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230804114425-if00:/dev/ttyACM0"

######################################
### giftpilz0.homelab.traefik

traefik_acme_challenge_type: dns
traefik_acme_dns_provider: "cloudflare"
traefik_log_level: "WARN"

# TCP entrypoints
traefik_tcp_entrypoints:
  - name: mqtt-tls
    port: 8883
  - name: mqtt
    port: 1883

# HTTP services
traefik_http_services:
  - name: homeassistant
    domain: homeassistant.nixpi.de
    rule: "Host(`homeassistant.nixpi.de`)"
    servers:
      - url: "http://homeassistant-pod:8123"
    tls_enabled: true
    acme_enabled: true

  - name: mqtt-websocket
    domain: mqtt.nixpi.de
    rule: "Host(`mqtt.nixpi.de`)"
    servers:
      - url: "http://mosquitto-pod:9001"
    tls_enabled: true
    acme_enabled: true

# TCP services
traefik_tcp_services:
  - name: mqtt
    domain: "mqtt.nixpi.de"
    rule: "HostSNI(`*`)"
    entrypoints:
      - mqtt
    servers:
      - address: "mosquitto-pod:1883"
    tls_enabled: false
    acme_enabled: false
    tls_passthrough: false

  - name: mqtt-tls
    domain: "mqtt.nixpi.de"
    rule: "HostSNI(`mqtt.nixpi.de`)"
    entrypoints:
      - mqtt-tls
    servers:
      - address: "mosquitto-pod:1883"
    tls_enabled: true
    acme_enabled: true
    tls_passthrough: false
