---
server:
  children:
    homeassistant:
      hosts:
        homeassistant.nixpi.de:
          ansible_host: 192.168.60.10
    vaultwarden:
      hosts:
        vaultwarden.nixpi.de:
          ansible_host: 192.168.60.11
    authentik:
      hosts:
        authentik.nixpi.de:
          ansible_host: 192.168.60.12
    forgejo:
      hosts:
        forgejo.nixpi.de:
          ansible_host: 192.168.60.13
    opencloud:
      hosts:
        opencloud.nixpi.de:
          ansible_host: 192.168.60.14
    bumper:
      hosts:
        bumper.nixpi.de:
          ansible_host: 192.168.60.15
  vars:
    ansible_port: 22
    ansible_user: serveradmin
