---
server:
  children:
    restic_server:
      hosts:
        pve.nixpi.de:
          ansible_host: 192.168.50.10
          ansible_user: root
    restic_clients:
      hosts:
        homeassistant.nixpi.de:
          ansible_host: 192.168.60.10
          ansible_user: serveradmin
        vaultwarden.nixpi.de:
          ansible_host: 192.168.60.11
          ansible_user: serveradmin
        misc.nixpi.de:
          ansible_host: 192.168.60.12
          ansible_user: serveradmin
        forgejo.nixpi.de:
          ansible_host: 192.168.60.13
          ansible_user: serveradmin
        opencloud.nixpi.de:
          ansible_host: 192.168.60.14
          ansible_user: serveradmin
        bumper.nixpi.de:
          ansible_host: 192.168.60.15
          ansible_user: serveradmin
