opencloud_admin_password: ENC[AES256_GCM,data:6OrGC4Tpmrtw5HLQ3R5Bdel6JNHlhYhKsq5SOw==,iv:GJ04l4CMRNRS4b/syX/F2Vgv5rebGvqR4r+aQNPWOQU=,tag:qTSM7QLeH2CsoCdpAIKCZw==,type:str]
forgejo_oauth_client_secret: ENC[AES256_GCM,data:4vQLzR93qwMaoKK/gbo+k7muv0RrEQBtOuwpz3E8hEVMNz9punYhxzM7RmXr5wWJ,iv:4eJAqWoczkHi1gSpUTHKwQWdFyTQk5NI14cLKcI1fZ0=,tag:fK5frKfN2Q02TOs1F0eXfA==,type:str]
traefik_acme_email: ENC[AES256_GCM,data:wps+AZHD18ynPuq/T9JLnamxZwSYulZ6Uho=,iv:hL986FDg5kH8ErYkRYwPe/A70xnBNlbmJfTkJtSSdWs=,tag:xE4JjIcA1+MxLREAhbE6rA==,type:str]
traefik_environment_vars:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:T70aesof48mKE8ybVFffW9qaSOMvJxrJV0wUqATdatEop5O03SJcsA==,iv:T4tpo4qEstFn4EjdZtzU2sVU43l1ybI/s5YTT9k43XM=,tag:8Bvz6jSNeOLn88KsElnZmA==,type:str]
sops:
    lastmodified: "2025-12-20T14:47:14Z"
    mac: ENC[AES256_GCM,data:FYO64GrNiexNJjUfZvfswbF47dat46XnqfmCpA91BtVs8FR7XYE48YlPHtBJn4xRi0hLyFCeEqmmGxMU1fT/kZJu8JtijUCsqnKKj2HjHOFSrTc4Qypi8XrbsFpRTamRleLQnYP1swZv0huo1NyURKxlu3t+oola6tZAl0do4eU=,iv:kDl4RJAA6yHhvox5wQgxFv1spdS1Zibkpt4qMQ3NZfo=,tag:JdIHNByJspbg1y9a+Aj6YA==,type:str]
    pgp:
        - created_at: "2025-12-20T14:38:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdA244ynC4WfNm8D2bjDRw56Do1ADn7Dkw+AcO7QlSDZw4w
            T2BjaGnFGJ0punv3hFTHr1mzYsRP7j1fuitIyThRP6EtbZ4hwqbbDgA1+RjDP0fS
            0l4B44wBOR64lTifR/80xE3fwhkammMoKtnLfMz9c4c7X5X/XuM8xCzqq6pziusL
            N1iOy+E+ESHmhRDsuIOUq+mEnzloYh2hmkz3CBbaMRA1YteybHE7QEZuR8+hAXC2
            =G2Dc
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.11.0
